import Head from 'next/head';
import Loader from '@/components/Loader';
import toast from 'react-hot-toast';

export default function Home() {
  return (
    <>
      <div></div>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* display toast succes message after clicking button */}
      <button onClick={() => toast.success('Success!')}>Success</button>
      <Loader show={true} />
    </>
  );
}
